In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/spaceship-titanic/sample_submission.csv
/kaggle/input/competitions/spaceship-titanic/train.csv
/kaggle/input/competitions/spaceship-titanic/test.csv

In [2]:
import pandas as pd

train = pd.read_csv("/kaggle/input/competitions/spaceship-titanic/train.csv")

train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [4]:
train["Transported"].value_counts(normalize=True) * 100

Transported
True     50.362361
False    49.637639
Name: proportion, dtype: float64

In [5]:
train.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [6]:
train["HomePlanet"].value_counts()

HomePlanet
Earth     4602
Europa    2131
Mars      1759
Name: count, dtype: int64

In [7]:
train["CryoSleep"].value_counts()

CryoSleep
False    5439
True     3037
Name: count, dtype: int64

In [8]:
train["Destination"].value_counts()

Destination
TRAPPIST-1e      5915
55 Cancri e      1800
PSO J318.5-22     796
Name: count, dtype: int64

In [9]:
train["VIP"].value_counts()

VIP
False    8291
True      199
Name: count, dtype: int64

In [10]:
train.groupby("CryoSleep")["Transported"].mean()

CryoSleep
False    0.328921
True     0.817583
Name: Transported, dtype: float64

In [11]:
train.groupby("HomePlanet")["Transported"].mean()

HomePlanet
Earth     0.423946
Europa    0.658846
Mars      0.523024
Name: Transported, dtype: float64

In [12]:
train.groupby("Destination")["Transported"].mean()

Destination
55 Cancri e      0.610000
PSO J318.5-22    0.503769
TRAPPIST-1e      0.471175
Name: Transported, dtype: float64

In [13]:
train.groupby("VIP")["Transported"].mean()

VIP
False    0.506332
True     0.381910
Name: Transported, dtype: float64

In [14]:
train["TotalSpend"] = train[
    ["RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]
].sum(axis=1)

train.groupby("Transported")["TotalSpend"].mean()

Transported
False    2004.149247
True      885.689127
Name: TotalSpend, dtype: float64

In [15]:
train["Cabin"].head(10)

0    B/0/P
1    F/0/S
2    A/0/S
3    A/0/S
4    F/1/S
5    F/0/P
6    F/2/S
7    G/0/S
8    F/3/S
9    B/1/P
Name: Cabin, dtype: object

In [16]:
train["Cabin"].str.split("/").str[0].value_counts()

Cabin
F    2794
G    2559
E     876
B     779
C     747
D     478
A     256
T       5
Name: count, dtype: int64

In [17]:
train["Deck"] = train["Cabin"].str.split("/").str[0]

train.groupby("Deck")["Transported"].mean()

Deck
A    0.496094
B    0.734275
C    0.680054
D    0.433054
E    0.357306
F    0.439871
G    0.516217
T    0.200000
Name: Transported, dtype: float64

In [18]:
train["Group"] = train["PassengerId"].str.split("_").str[0]

train["Group"].value_counts().head(10)

Group
9081    8
4005    8
8988    8
5133    8
4256    8
4498    8
8956    8
8796    8
0984    8
5885    8
Name: count, dtype: int64

In [19]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Features and target
X = train.drop(columns=["Transported", "TotalSpend", "Deck", "Group"])
y = train["Transported"]

# Remove identifiers/text that we are not using as predictive features
X = X.drop(columns=["PassengerId", "Name"])

# Separate numerical and categorical columns
numeric_features = X.select_dtypes(include=["int64", "float64"]).columns
categorical_features = X.select_dtypes(include=["object"]).columns

# Numerical: fill missing values with median
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])
# Categorical: fill missing values with most frequent value, then encode
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine preprocessing
preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

# Logistic Regression model
baseline_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])

# 5-fold cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(
    baseline_model,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("Fold scores:", scores)
print("Mean CV accuracy:", scores.mean())
print("Standard deviation:", scores.std())

Fold scores: [0.79125934 0.77975848 0.80103508 0.78711162 0.77733026]
Mean CV accuracy: 0.787298958238899
Standard deviation: 0.008492754142349082

In [20]:
test = pd.read_csv(
    "/kaggle/input/competitions/spaceship-titanic/test.csv"
)

test.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [21]:
X_test = test.drop(columns=["PassengerId", "Name"])

In [22]:
baseline_model.fit(X, y)

test_predictions = baseline_model.predict(X_test)

test_predictions[:10]

array([ True, False,  True,  True, False,  True,  True,  True,  True,
        True])

In [23]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Transported": test_predictions
})

submission.to_csv("/kaggle/working/submission_baseline.csv", index=False)

submission.head()

  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01        False

In [24]:
# ============================================================
# EXPERIMENT 2: Add TotalSpend Feature
# Hypothesis: Total spending may improve prediction because
# transported and non-transported passengers show different
# spending patterns.
# ============================================================

X = train.drop(columns=["Transported", "Deck", "Group", "PassengerId", "Name"])
y = train["Transported"]

In [25]:
X.columns

Index(['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age', 'VIP',
       'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'TotalSpend'],
      dtype='object')

In [26]:
# ============================================================
# EXPERIMENT 2: Preprocessing with TotalSpend
# ============================================================

numeric_features_exp2 = X.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_exp2 = X.select_dtypes(
    include=["object"]
).columns

numeric_pipeline_exp2 = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline_exp2 = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_exp2 = ColumnTransformer([
    ("num", numeric_pipeline_exp2, numeric_features_exp2),
    ("cat", categorical_pipeline_exp2, categorical_features_exp2)
])

model_exp2 = Pipeline([
    ("preprocessor", preprocessor_exp2),
    ("model", LogisticRegression(max_iter=5000))
])

In [27]:
# ============================================================
# EXPERIMENT 2: Evaluate TotalSpend Feature
# ============================================================

scores_exp2 = cross_val_score(
    model_exp2,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("Fold scores:", scores_exp2)
print("Mean CV accuracy:", scores_exp2.mean())
print("Standard deviation:", scores_exp2.std())

Fold scores: [0.79183439 0.77975848 0.80103508 0.787687   0.77733026]
Mean CV accuracy: 0.7875290416631651
Standard deviation: 0.008548340331594968

In [28]:
# ============================================================
# EXPERIMENT 2: Add TotalSpend to Test Data
# ============================================================

test["TotalSpend"] = test[
    ["RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]
].sum(axis=1)

X_test = test.drop(columns=["PassengerId", "Name"])

In [29]:
# Train Experiment 2 on all training data
model_exp2.fit(X, y)

# Predict the test data
predictions_exp2 = model_exp2.predict(X_test)

predictions_exp2[:10]

array([ True, False,  True,  True, False,  True,  True,  True,  True,
        True])

In [30]:
# ============================================================
# EXPERIMENT 2: Create Submission
# ============================================================

submission_exp2 = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Transported": predictions_exp2
})

submission_exp2.to_csv(
    "/kaggle/working/submission_exp2.csv",
    index=False
)

submission_exp2.head()

  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01        False

In [31]:
# ============================================================
# EXPERIMENT 3: Cabin Features
# Hypothesis: Cabin deck and side may help predict Transported.
# ============================================================

train["Deck"] = train["Cabin"].str.split("/").str[0]
train["Side"] = train["Cabin"].str.split("/").str[2]

train[["Cabin", "Deck", "Side"]].head(10)

   Cabin Deck Side
0  B/0/P    B    P
1  F/0/S    F    S
2  A/0/S    A    S
3  A/0/S    A    S
4  F/1/S    F    S
5  F/0/P    F    P
6  F/2/S    F    S
7  G/0/S    G    S
8  F/3/S    F    S
9  B/1/P    B    P

In [32]:
train.groupby("Deck")["Transported"].mean()

Deck
A    0.496094
B    0.734275
C    0.680054
D    0.433054
E    0.357306
F    0.439871
G    0.516217
T    0.200000
Name: Transported, dtype: float64

In [33]:
train.groupby("Side")["Transported"].mean()

Side
P    0.451260
S    0.555037
Name: Transported, dtype: float64

In [34]:
# EXPERIMENT 3: Cabin Features (Deck + Side)
# ============================================================

# Create Deck and Side from Cabin in TRAINING data
train["Deck"] = train["Cabin"].str.split("/").str[0]
train["Side"] = train["Cabin"].str.split("/").str[2]

# Create Deck and Side from Cabin in TEST data
test["Deck"] = test["Cabin"].str.split("/").str[0]
test["Side"] = test["Cabin"].str.split("/").str[2]


# ============================================================
# Prepare training data
# ============================================================

X = train.drop(
    columns=[
        "Transported",
        "TotalSpend",
        "Group",
        "PassengerId",
        "Name",
        "Cabin"
    ]
)

y = train["Transported"]


# ============================================================
# Features
# ============================================================

numeric_features_exp3 = X.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_exp3 = X.select_dtypes(
    include=["object"]
).columns


# ============================================================
# Numeric pipeline
# ============================================================

numeric_pipeline_exp3 = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])


# ============================================================
# Categorical pipeline
# ============================================================

categorical_pipeline_exp3 = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])


# ============================================================
# Preprocessor
# ============================================================

preprocessor_exp3 = ColumnTransformer([
    ("num", numeric_pipeline_exp3, numeric_features_exp3),
    ("cat", categorical_pipeline_exp3, categorical_features_exp3)
])


# ============================================================
# Model
# ============================================================

model_exp3 = Pipeline([
    ("preprocessor", preprocessor_exp3),
    ("model", LogisticRegression(max_iter=5000))
])

In [35]:
# Cross-validation
# ============================================================

scores_exp3 = cross_val_score(
    model_exp3,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("Fold scores:", scores_exp3)
print("Mean CV accuracy:", scores_exp3.mean())
print("CV standard deviation:", scores_exp3.std())

Fold scores: [0.78895917 0.78378378 0.79643473 0.80552359 0.77905639]
Mean CV accuracy: 0.7907515330623329
CV standard deviation: 0.009370709376074635

In [36]:
# ============================================================
# EXPERIMENT 3: Create Submission
# ============================================================

X_test_exp3 = test.drop(
    columns=[
        "Cabin",
        "PassengerId",
        "Name",
        "TotalSpend",
        "Group"
    ],
    errors="ignore"
)

# Make sure training and test columns are identical
X_test_exp3 = X_test_exp3[X.columns]


# ============================================================
# Train on all training data
# ============================================================

model_exp3.fit(X, y)


# ============================================================
# Predict test data
# ============================================================

predictions_exp3 = model_exp3.predict(X_test_exp3)


# ============================================================
# Create submission
# ============================================================

submission_exp3 = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Transported": predictions_exp3
})


# ============================================================
# Save submission
# ============================================================

submission_exp3.to_csv(
    "/kaggle/working/submission_exp3.csv",
    index=False
)


# ============================================================
# Check submission
# ============================================================

print("\nSubmission created successfully!")
print(submission_exp3.head())
print("Number of predictions:", len(predictions_exp3))

Submission created successfully!
  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01         True
Number of predictions: 4277

In [37]:
# ============================================================
# EXPERIMENT 4: Group Size
# Hypothesis: Group size may help predict Transported.
# ============================================================

train["Group"] = train["PassengerId"].str.split("_").str[0]

train["GroupSize"] = train["Group"].map(
    train["Group"].value_counts()
)

train[["PassengerId", "Group", "GroupSize"]].head(10)

  PassengerId Group  GroupSize
0     0001_01  0001          1
1     0002_01  0002          1
2     0003_01  0003          2
3     0003_02  0003          2
4     0004_01  0004          1
5     0005_01  0005          1
6     0006_01  0006          2
7     0006_02  0006          2
8     0007_01  0007          1
9     0008_01  0008          3

In [38]:
train.groupby("GroupSize")["Transported"].mean()

GroupSize
1    0.452445
2    0.538050
3    0.593137
4    0.640777
5    0.592453
6    0.614943
7    0.541126
8    0.394231
Name: Transported, dtype: float64

In [39]:
# ============================================================
# EXPERIMENT 4: GroupSize
# ============================================================

X = train.drop(
    columns=[
        "Transported",
        "Cabin",
        "TotalSpend",
        "Group",
        "PassengerId",
        "Name"
    ]
)

y = train["Transported"]

numeric_features_exp4 = X.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_exp4 = X.select_dtypes(
    include=["object"]
).columns

numeric_pipeline_exp4 = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline_exp4 = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_exp4 = ColumnTransformer([
    ("num", numeric_pipeline_exp4, numeric_features_exp4),
    ("cat", categorical_pipeline_exp4, categorical_features_exp4)
])

model_exp4 = Pipeline([
    ("preprocessor", preprocessor_exp4),
    ("model", LogisticRegression(max_iter=5000))
])

In [40]:
scores_exp4 = cross_val_score(
    model_exp4,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("Fold scores:", scores_exp4)
print("Mean CV accuracy:", scores_exp4.mean())
print("CV standard deviation:", scores_exp4.std())

Fold scores: [0.78895917 0.78435883 0.79643473 0.80552359 0.77905639]
Mean CV accuracy: 0.7908665416879799
CV standard deviation: 0.009287647689807641

In [41]:
# ============================================================
# EXPERIMENT 4: Create Submission
# ============================================================

test["Group"] = test["PassengerId"].str.split("_").str[0]

test["GroupSize"] = test["Group"].map(
    test["Group"].value_counts()
)

X_test_exp4 = test.drop(
    columns=[
        "PassengerId",
        "Name",
        "Cabin",
        "TotalSpend",
        "Group"
    ]
)

model_exp4.fit(X, y)

predictions_exp4 = model_exp4.predict(X_test_exp4)

submission_exp4 = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Transported": predictions_exp4
})

submission_exp4.to_csv(
    "/kaggle/working/submission_exp4.csv",
    index=False
)

submission_exp4.head()

  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01         True

In [42]:
# ============================================================
# EXPERIMENT 5: Random Forest
# Change: Only the model
# Hypothesis: Random Forest can learn more complex relationships.
# ============================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score
import pandas as pd


# ============================================================
# 1. Prepare Training Data
# ============================================================

X = train.drop(
    columns=[
        "Transported",
        "TotalSpend",
        "Deck",
        "Side",
        "Group",
        "PassengerId",
        "Name"
    ],
    errors="ignore"
)

y = train["Transported"]


# ============================================================
# 2. Identify Numeric and Categorical Features
# ============================================================

numeric_features_exp5 = X.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_exp5 = X.select_dtypes(
    include=["object"]
).columns


# ============================================================
# 3. Numeric Pipeline
# ============================================================

numeric_pipeline_exp5 = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])


# ============================================================
# 4. Categorical Pipeline
# ============================================================

categorical_pipeline_exp5 = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])


# ============================================================
# 5. Preprocessor
# ============================================================

preprocessor_exp5 = ColumnTransformer([
    ("num", numeric_pipeline_exp5, numeric_features_exp5),
    ("cat", categorical_pipeline_exp5, categorical_features_exp5)
])


# ============================================================
# 6. Random Forest Model
# ============================================================

model_exp5 = Pipeline([
    ("preprocessor", preprocessor_exp5),
    ("model", RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ))
])


# ============================================================
# 7. Cross-Validation
# ============================================================

scores_exp5 = cross_val_score(
    model_exp5,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("============================================================")
print("EXPERIMENT 5: RANDOM FOREST RESULTS")
print("============================================================")

print("Fold scores:", scores_exp5)
print("Mean CV accuracy:", scores_exp5.mean())
print("Accuracy (%):", scores_exp5.mean() * 100)
print("CV standard deviation:", scores_exp5.std())


# ============================================================
# 8. Prepare Test Data
# ============================================================

X_test_exp5 = test.drop(
    columns=[
        "Transported",
        "TotalSpend",
        "Deck",
        "Side",
        "Group",
        "PassengerId",
        "Name"
    ],
    errors="ignore"
)


# Make sure test has exactly the same features as training
X_test_exp5 = X_test_exp5[X.columns]


# ============================================================
# 9. Train on ALL Training Data
# ============================================================

model_exp5.fit(X, y)


# ============================================================
# 10. Predict Test Data
# ============================================================

predictions_exp5 = model_exp5.predict(X_test_exp5)


# ============================================================
# 11. Create Submission
# ============================================================

submission_exp5 = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Transported": predictions_exp5
})


# ============================================================
# 12. Save Submission
# ============================================================

submission_exp5.to_csv(
    "/kaggle/working/submission_exp5.csv",
    index=False
)


# ============================================================
# 13. Display Submission
# ============================================================

print("\n============================================================")
print("SUBMISSION CREATED SUCCESSFULLY")
print("============================================================")

print(submission_exp5.head())

print("\nNumber of predictions:", len(predictions_exp5))

print("\nFile saved to:")
print("/kaggle/working/submission_exp5.csv")

============================================================
EXPERIMENT 5: RANDOM FOREST RESULTS
============================================================
Fold scores: [0.79988499 0.78090857 0.79298447 0.78941312 0.78998849]
Mean CV accuracy: 0.7906359288799364
Accuracy (%): 79.06359288799364
CV standard deviation: 0.00612530499399508

============================================================
SUBMISSION CREATED SUCCESSFULLY
============================================================
  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01         True

Number of predictions: 4277

File saved to:
/kaggle/working/submission_exp5.csv

In [43]:
import pandas as pd

# Load the training dataset
train = pd.read_csv("/kaggle/input/competitions/spaceship-titanic/train.csv")

# Display the first 5 rows
train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [44]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [45]:
# ============================================================
# HANDLE MISSING VALUES
# ============================================================

# Numerical columns → median
numeric_columns = train.select_dtypes(
    include=["int64", "float64"]
).columns

for column in numeric_columns:
    train[column] = train[column].fillna(train[column].median())

# Categorical columns → most frequent value
categorical_columns = train.select_dtypes(
    include=["object"]
).columns

for column in categorical_columns:
    train[column] = train[column].fillna(
        train[column].mode()[0]
    ).infer_objects(copy=False)

# Check missing values
print("Missing values after cleaning:")
print(train.isnull().sum())

Missing values after cleaning:
PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

/tmp/ipykernel_16/2689514865.py:19: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train[column] = train[column].fillna(

In [46]:
train["Transported"].value_counts()

Transported
True     4378
False    4315
Name: count, dtype: int64

In [47]:
train.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000
mean,28.790291,220.009318,448.434027,169.572300,304.588865,298.261820
std,14.341404,660.519050,1595.790627,598.007164,1125.562559,1134.126417
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,37.000000,41.000000,61.000000,22.000000,53.000000,40.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [48]:
train.select_dtypes(include=["object"]).nunique()

PassengerId    8693
HomePlanet        3
Cabin          6560
Destination       3
Name           8473
dtype: int64

In [49]:
train.duplicated().sum()

np.int64(0)

In [50]:
train.dtypes

PassengerId      object
HomePlanet       object
CryoSleep          bool
Cabin            object
Destination      object
Age             float64
VIP                bool
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

In [51]:
# ============================================================
# STEP 4: DATA PREPROCESSING
# Step 1: Separate features (X) and target (y)
# ============================================================

X = train.drop(columns=["Transported"])
y = train["Transported"]

# Remove identifiers that we don't want the models to learn from
X = X.drop(columns=["PassengerId", "Name"])

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (8693, 11)
Target shape: (8693,)

In [52]:
# Identify numerical and categorical features

numeric_features = X.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features = X.select_dtypes(
    include=["object", "bool"]
).columns

print("Numerical features:")
print(list(numeric_features))

print("\nCategorical features:")
print(list(categorical_features))

Numerical features:
['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']

Categorical features:
['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP']

In [53]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Numerical preprocessing
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# Categorical preprocessing
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine both
preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

print("Preprocessing pipeline created successfully.")

Preprocessing pipeline created successfully.

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Validation set:", X_val.shape)

Training set: (6954, 11)
Validation set: (1739, 11)

In [55]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

baseline_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=5000))
])

# Train the model
baseline_model.fit(X_train, y_train)

print("Logistic Regression trained successfully.")

Logistic Regression trained successfully.

In [56]:
from sklearn.metrics import accuracy_score

# Make predictions on validation data
y_pred = baseline_model.predict(X_val)

# Calculate accuracy
accuracy = accuracy_score(y_val, y_pred)

print("Logistic Regression Accuracy:", accuracy)
print("Accuracy (%):", accuracy * 100)

Logistic Regression Accuracy: 0.7860839562967222
Accuracy (%): 78.60839562967222

In [57]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", KNeighborsClassifier(n_neighbors=5))
])

# Train KNN
knn_model.fit(X_train, y_train)

# Predict validation data
y_pred_knn = knn_model.predict(X_val)

# Evaluate
knn_accuracy = accuracy_score(y_val, y_pred_knn)

print("KNN Accuracy:", knn_accuracy)
print("Accuracy (%):", knn_accuracy * 100)

KNN Accuracy: 0.7613571017826337
Accuracy (%): 76.13571017826337

In [58]:
from sklearn.svm import SVC

svm_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", SVC(
        kernel="rbf",
        C=1.0,
        random_state=42
    ))
])

# Train SVM
svm_model.fit(X_train, y_train)

# Predict validation data
y_pred_svm = svm_model.predict(X_val)

# Evaluate
svm_accuracy = accuracy_score(y_val, y_pred_svm)

print("SVM Accuracy:", svm_accuracy)
print("Accuracy (%):", svm_accuracy * 100)

SVM Accuracy: 0.7786083956296722
Accuracy (%): 77.86083956296721

In [59]:
from sklearn.ensemble import RandomForestClassifier

random_forest_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ))
])

# Train Random Forest
random_forest_model.fit(X_train, y_train)

# Predict validation data
y_pred_rf = random_forest_model.predict(X_val)

# Evaluate
rf_accuracy = accuracy_score(y_val, y_pred_rf)

print("Random Forest Accuracy:", rf_accuracy)
print("Accuracy (%):", rf_accuracy * 100)

Random Forest Accuracy: 0.7878090856814262
Accuracy (%): 78.78090856814262

In [60]:
from sklearn.ensemble import GradientBoostingClassifier

gradient_boosting_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", GradientBoostingClassifier(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=3,
        random_state=42
    ))
])

# Train Gradient Boosting
gradient_boosting_model.fit(X_train, y_train)

# Predict validation data
y_pred_gb = gradient_boosting_model.predict(X_val)

# Evaluate
gb_accuracy = accuracy_score(y_val, y_pred_gb)

print("Gradient Boosting Accuracy:", gb_accuracy)
print("Accuracy (%):", gb_accuracy * 100)

Gradient Boosting Accuracy: 0.7964347326049454
Accuracy (%): 79.64347326049453

In [61]:
# ============================================================
# MODEL 6: XGBoost
# ============================================================

from xgboost import XGBClassifier

xgb_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    ))
])

# Train
xgb_model.fit(X_train, y_train)

# Predict
y_pred_xgb = xgb_model.predict(X_val)

# Evaluate
xgb_accuracy = accuracy_score(y_val, y_pred_xgb)

print("XGBoost Accuracy:", xgb_accuracy)
print("Accuracy (%):", xgb_accuracy * 100)

XGBoost Accuracy: 0.8039102932719954
Accuracy (%): 80.39102932719953

In [62]:
# ============================================================
# MODEL 7: HistGradientBoosting
# ============================================================

from sklearn.ensemble import HistGradientBoostingClassifier

# Dense categorical preprocessing
categorical_pipeline_hist = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False
    ))
])

# Preprocessor that produces dense data
preprocessor_hist = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline_hist, categorical_features)
])

# HistGradientBoosting model
hist_model = Pipeline([
    ("preprocessor", preprocessor_hist),
    ("model", HistGradientBoostingClassifier(
        max_iter=300,
        learning_rate=0.05,
        max_leaf_nodes=31,
        random_state=42
    ))
])

# Train
hist_model.fit(X_train, y_train)

# Predict
y_pred_hist = hist_model.predict(X_val)

# Evaluate
hist_accuracy = accuracy_score(y_val, y_pred_hist)

print("HistGradientBoosting Accuracy:", hist_accuracy)
print("Accuracy (%):", hist_accuracy * 100)

HistGradientBoosting Accuracy: 0.7993099482461185
Accuracy (%): 79.93099482461184

In [63]:
# ============================================================
# MODEL 8: Extra Trees Classifier
# ============================================================

from sklearn.ensemble import ExtraTreesClassifier

extra_trees_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", ExtraTreesClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1,
        max_features="sqrt"
    ))
])

# Train
extra_trees_model.fit(X_train, y_train)

# Predict
y_pred_extra = extra_trees_model.predict(X_val)

# Evaluate
extra_accuracy = accuracy_score(y_val, y_pred_extra)

print("Extra Trees Accuracy:", extra_accuracy)
print("Accuracy (%):", extra_accuracy * 100)

Extra Trees Accuracy: 0.7625071880391029
Accuracy (%): 76.25071880391029

In [64]:
# ============================================================
# FEATURE ENGINEERING 1: TotalSpend
# ============================================================

train["TotalSpend"] = train[
    ["RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]
].sum(axis=1)

print(train[["RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck", "TotalSpend"]].head())

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  TotalSpend
0          0.0        0.0           0.0     0.0     0.0         0.0
1        109.0        9.0          25.0   549.0    44.0       736.0
2         43.0     3576.0           0.0  6715.0    49.0     10383.0
3          0.0     1283.0         371.0  3329.0   193.0      5176.0
4        303.0       70.0         151.0   565.0     2.0      1091.0

In [65]:
# ============================================================
# FEATURE ENGINEERING 1: Test TotalSpend with XGBoost
# ============================================================

X_fe1 = train.drop(columns=["Transported", "PassengerId", "Name"])

y_fe1 = train["Transported"]

# Split using the same 80/20 approach
X_train_fe1, X_val_fe1, y_train_fe1, y_val_fe1 = train_test_split(
    X_fe1,
    y_fe1,
    test_size=0.20,
    random_state=42,
    stratify=y_fe1
)

# Identify features
numeric_features_fe1 = X_fe1.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_fe1 = X_fe1.select_dtypes(
    include=["object", "bool"]
).columns

# Preprocessing
numeric_pipeline_fe1 = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_pipeline_fe1 = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_fe1 = ColumnTransformer([
    ("num", numeric_pipeline_fe1, numeric_features_fe1),
    ("cat", categorical_pipeline_fe1, categorical_features_fe1)
])

# XGBoost
xgb_fe1 = Pipeline([
    ("preprocessor", preprocessor_fe1),
    ("model", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    ))
])

# Train
xgb_fe1.fit(X_train_fe1, y_train_fe1)

# Predict
y_pred_fe1 = xgb_fe1.predict(X_val_fe1)

# Evaluate
accuracy_fe1 = accuracy_score(y_val_fe1, y_pred_fe1)

print("XGBoost + TotalSpend Accuracy:", accuracy_fe1)
print("Accuracy (%):", accuracy_fe1 * 100)

XGBoost + TotalSpend Accuracy: 0.8004600345025877
Accuracy (%): 80.04600345025878

In [66]:
# ============================================================
# FEATURE ENGINEERING 2: Deck + XGBoost
# ============================================================

# Create Deck from Cabin
train["Deck"] = train["Cabin"].str.split("/").str[0]

# Features: add Deck, but do not use TotalSpend
X_fe2 = train.drop(
    columns=["Transported", "PassengerId", "Name", "TotalSpend", "Cabin"]
)

y_fe2 = train["Transported"]

# 80% Training / 20% Validation
X_train_fe2, X_val_fe2, y_train_fe2, y_val_fe2 = train_test_split(
    X_fe2,
    y_fe2,
    test_size=0.20,
    random_state=42,
    stratify=y_fe2
)

# Identify numerical and categorical features
numeric_features_fe2 = X_fe2.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_fe2 = X_fe2.select_dtypes(
    include=["object", "bool"]
).columns

# Preprocessing
numeric_pipeline_fe2 = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_pipeline_fe2 = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_fe2 = ColumnTransformer([
    ("num", numeric_pipeline_fe2, numeric_features_fe2),
    ("cat", categorical_pipeline_fe2, categorical_features_fe2)
])

# XGBoost
xgb_fe2 = Pipeline([
    ("preprocessor", preprocessor_fe2),
    ("model", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    ))
])

# Train
xgb_fe2.fit(X_train_fe2, y_train_fe2)

# Predict
y_pred_fe2 = xgb_fe2.predict(X_val_fe2)

# Evaluate
accuracy_fe2 = accuracy_score(y_val_fe2, y_pred_fe2)

print("XGBoost + Deck Accuracy:", accuracy_fe2)
print("Accuracy (%):", accuracy_fe2 * 100)

XGBoost + Deck Accuracy: 0.8067855089131685
Accuracy (%): 80.67855089131685

In [67]:
train["Side"] = train["Cabin"].str.split("/").str[2]

train.groupby("Side")["Transported"].mean()

Side
P    0.451260
S    0.552708
Name: Transported, dtype: float64

In [68]:
# ============================================================
# FEATURE ENGINEERING 3: Deck + Side + XGBoost
# ============================================================

# Features
X_fe3 = train.drop(
    columns=[
        "Transported",
        "PassengerId",
        "Name",
        "TotalSpend",
        "Cabin"
    ]
)

y_fe3 = train["Transported"]

# 80% Training / 20% Validation
X_train_fe3, X_val_fe3, y_train_fe3, y_val_fe3 = train_test_split(
    X_fe3,
    y_fe3,
    test_size=0.20,
    random_state=42,
    stratify=y_fe3
)

# Identify features
numeric_features_fe3 = X_fe3.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_fe3 = X_fe3.select_dtypes(
    include=["object", "bool"]
).columns

# Preprocessing
numeric_pipeline_fe3 = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_pipeline_fe3 = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_fe3 = ColumnTransformer([
    ("num", numeric_pipeline_fe3, numeric_features_fe3),
    ("cat", categorical_pipeline_fe3, categorical_features_fe3)
])

# XGBoost
xgb_fe3 = Pipeline([
    ("preprocessor", preprocessor_fe3),
    ("model", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    ))
])

# Train
xgb_fe3.fit(X_train_fe3, y_train_fe3)

# Predict
y_pred_fe3 = xgb_fe3.predict(X_val_fe3)

# Evaluate
accuracy_fe3 = accuracy_score(y_val_fe3, y_pred_fe3)

print("XGBoost + Deck + Side Accuracy:", accuracy_fe3)
print("Accuracy (%):", accuracy_fe3 * 100)

XGBoost + Deck + Side Accuracy: 0.8131109833237493
Accuracy (%): 81.31109833237493

In [69]:
# ============================================================
# FEATURE ENGINEERING 4: Deck + Side + GroupSize + XGBoost
# ============================================================

# Create Group ID
train["Group"] = train["PassengerId"].str.split("_").str[0]

# Create GroupSize
train["GroupSize"] = train["Group"].map(
    train["Group"].value_counts()
)

# Features
X_fe4 = train.drop(
    columns=[
        "Transported",
        "PassengerId",
        "Name",
        "TotalSpend",
        "Cabin",
        "Group"
    ]
)

y_fe4 = train["Transported"]

# 80% Training / 20% Validation
X_train_fe4, X_val_fe4, y_train_fe4, y_val_fe4 = train_test_split(
    X_fe4,
    y_fe4,
    test_size=0.20,
    random_state=42,
    stratify=y_fe4
)

# Identify features
numeric_features_fe4 = X_fe4.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_fe4 = X_fe4.select_dtypes(
    include=["object", "bool"]
).columns

# Preprocessing
numeric_pipeline_fe4 = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_pipeline_fe4 = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_fe4 = ColumnTransformer([
    ("num", numeric_pipeline_fe4, numeric_features_fe4),
    ("cat", categorical_pipeline_fe4, categorical_features_fe4)
])

# XGBoost
xgb_fe4 = Pipeline([
    ("preprocessor", preprocessor_fe4),
    ("model", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    ))
])

# Train
xgb_fe4.fit(X_train_fe4, y_train_fe4)

# Predict
y_pred_fe4 = xgb_fe4.predict(X_val_fe4)

# Evaluate
accuracy_fe4 = accuracy_score(y_val_fe4, y_pred_fe4)

print("XGBoost + Deck + Side + GroupSize Accuracy:", accuracy_fe4)
print("Accuracy (%):", accuracy_fe4 * 100)

XGBoost + Deck + Side + GroupSize Accuracy: 0.8108108108108109
Accuracy (%): 81.08108108108108

In [70]:
xgb_tuned_1 = Pipeline([
    ("preprocessor", preprocessor_fe3),
    ("model", XGBClassifier(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=5,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    ))
])

xgb_tuned_1.fit(X_train_fe3, y_train_fe3)

y_pred_tuned_1 = xgb_tuned_1.predict(X_val_fe3)

accuracy_tuned_1 = accuracy_score(
    y_val_fe3,
    y_pred_tuned_1
)

print("Tuned XGBoost Accuracy:", accuracy_tuned_1)
print("Accuracy (%):", accuracy_tuned_1 * 100)

Tuned XGBoost Accuracy: 0.8085106382978723
Accuracy (%): 80.85106382978722

In [71]:
xgb_tuned_2 = Pipeline([
    ("preprocessor", preprocessor_fe3),
    ("model", XGBClassifier(
        n_estimators=500,
        learning_rate=0.03,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    ))
])

xgb_tuned_2.fit(X_train_fe3, y_train_fe3)

y_pred_tuned_2 = xgb_tuned_2.predict(X_val_fe3)

accuracy_tuned_2 = accuracy_score(
    y_val_fe3,
    y_pred_tuned_2
)

print("Tuned XGBoost 2 Accuracy:", accuracy_tuned_2)
print("Accuracy (%):", accuracy_tuned_2 * 100)

Tuned XGBoost 2 Accuracy: 0.81196089706728
Accuracy (%): 81.196089706728

In [72]:
xgb_tuned_3 = Pipeline([
    ("preprocessor", preprocessor_fe3),
    ("model", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.9,
        random_state=42,
        eval_metric="logloss"
    ))
])

xgb_tuned_3.fit(X_train_fe3, y_train_fe3)

y_pred_tuned_3 = xgb_tuned_3.predict(X_val_fe3)

accuracy_tuned_3 = accuracy_score(
    y_val_fe3,
    y_pred_tuned_3
)

print("Tuned XGBoost 3 Accuracy:", accuracy_tuned_3)
print("Accuracy (%):", accuracy_tuned_3 * 100)

Tuned XGBoost 3 Accuracy: 0.8142610695802185
Accuracy (%): 81.42610695802185

In [73]:
test = pd.read_csv(
    "/kaggle/input/competitions/spaceship-titanic/test.csv"
)

test.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [74]:
test["Deck"] = test["Cabin"].str.split("/").str[0]
test["Side"] = test["Cabin"].str.split("/").str[2]

test[["PassengerId", "Cabin", "Deck", "Side"]].head()

  PassengerId  Cabin Deck Side
0     0013_01  G/3/S    G    S
1     0018_01  F/4/S    F    S
2     0019_01  C/0/S    C    S
3     0021_01  C/1/S    C    S
4     0023_01  F/5/S    F    S

In [75]:
X_test_final = test.drop(
    columns=[
        "PassengerId",
        "Name",
        "Cabin"
    ]
)

X_test_final.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Deck,Side
0,Earth,True,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,G,S
1,Earth,False,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,F,S
2,Europa,True,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,C,S
3,Europa,False,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,C,S
4,Earth,False,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,F,S

In [76]:
X_test_final = test.drop(
    columns=[
        "PassengerId",
        "Name",
        "Cabin"
    ]
)

X_test_final.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Deck,Side
0,Earth,True,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,G,S
1,Earth,False,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,F,S
2,Europa,True,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,C,S
3,Europa,False,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,C,S
4,Earth,False,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,F,S

In [77]:
y_test_pred = xgb_tuned_3.predict(X_test_final)

# Convert 1/0 to True/False
y_test_pred = y_test_pred.astype(bool)

print("Number of predictions:", len(y_test_pred))
print("First 10 predictions:")
print(y_test_pred[:10])

Number of predictions: 4277
First 10 predictions:
[ True False  True  True  True  True  True  True  True  True]

In [78]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Transported": y_test_pred
})

submission.head()

  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01         True

In [79]:
submission.to_csv("submission.csv", index=False)

print("Submission file created successfully!")
print("Rows:", len(submission))

Submission file created successfully!
Rows: 4277

In [80]:
# Create Surname from Name
train["Surname"] = train["Name"].str.split().str[-1]

# Features: keep our best Deck + Side and add Surname
X_fe5 = train.drop(
    columns=[
        "Transported",
        "PassengerId",
        "Name",
        "Cabin",
        "TotalSpend",
        "Group",
        "GroupSize"
    ]
)

y_fe5 = train["Transported"]

X_train_fe5, X_val_fe5, y_train_fe5, y_val_fe5 = train_test_split(
    X_fe5,
    y_fe5,
    test_size=0.20,
    random_state=42,
    stratify=y_fe5
)

numeric_features_fe5 = X_fe5.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_fe5 = X_fe5.select_dtypes(
    include=["object", "bool"]
).columns

preprocessor_fe5 = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), numeric_features_fe5),

    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]), categorical_features_fe5)
])

xgb_fe5 = Pipeline([
    ("preprocessor", preprocessor_fe5),
    ("model", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.9,
        random_state=42,
        eval_metric="logloss"
    ))
])

xgb_fe5.fit(X_train_fe5, y_train_fe5)

y_pred_fe5 = xgb_fe5.predict(X_val_fe5)

accuracy_fe5 = accuracy_score(
    y_val_fe5,
    y_pred_fe5
)

print("XGBoost + Deck + Side + Surname Accuracy:", accuracy_fe5)
print("Accuracy (%):", accuracy_fe5 * 100)

XGBoost + Deck + Side + Surname Accuracy: 0.8096607245543416
Accuracy (%): 80.96607245543416

In [81]:
train["Group"] = train["PassengerId"].str.split("_").str[0]

X_fe6 = train.drop(
    columns=[
        "Transported",
        "PassengerId",
        "Name",
        "Cabin",
        "TotalSpend",
        "GroupSize",
        "Surname"
    ]
)

y_fe6 = train["Transported"]

X_train_fe6, X_val_fe6, y_train_fe6, y_val_fe6 = train_test_split(
    X_fe6,
    y_fe6,
    test_size=0.20,
    random_state=42,
    stratify=y_fe6
)

numeric_features_fe6 = X_fe6.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_fe6 = X_fe6.select_dtypes(
    include=["object", "bool"]
).columns

preprocessor_fe6 = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), numeric_features_fe6),

    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]), categorical_features_fe6)
])

xgb_fe6 = Pipeline([
    ("preprocessor", preprocessor_fe6),
    ("model", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.9,
        random_state=42,
        eval_metric="logloss"
    ))
])

xgb_fe6.fit(X_train_fe6, y_train_fe6)

y_pred_fe6 = xgb_fe6.predict(X_val_fe6)

accuracy_fe6 = accuracy_score(y_val_fe6, y_pred_fe6)

print("XGBoost + Deck + Side + Group Accuracy:", accuracy_fe6)
print("Accuracy (%):", accuracy_fe6 * 100)

XGBoost + Deck + Side + Group Accuracy: 0.8113858539390454
Accuracy (%): 81.13858539390453

In [82]:
# Count how many spending categories have a value greater than 0
spending_columns = [
    "RoomService",
    "FoodCourt",
    "ShoppingMall",
    "Spa",
    "VRDeck"
]

train["SpendingCategories"] = (
    train[spending_columns] > 0
).sum(axis=1)

X_fe7 = train.drop(
    columns=[
        "Transported",
        "PassengerId",
        "Name",
        "Cabin",
        "TotalSpend",
        "Group",
        "GroupSize",
        "Surname"
    ]
)

y_fe7 = train["Transported"]

X_train_fe7, X_val_fe7, y_train_fe7, y_val_fe7 = train_test_split(
    X_fe7,
    y_fe7,
    test_size=0.20,
    random_state=42,
    stratify=y_fe7
)

numeric_features_fe7 = X_fe7.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features_fe7 = X_fe7.select_dtypes(
    include=["object", "bool"]
).columns

preprocessor_fe7 = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), numeric_features_fe7),

    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]), categorical_features_fe7)
])

xgb_fe7 = Pipeline([
    ("preprocessor", preprocessor_fe7),
    ("model", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.9,
        random_state=42,
        eval_metric="logloss"
    ))
])

xgb_fe7.fit(X_train_fe7, y_train_fe7)

y_pred_fe7 = xgb_fe7.predict(X_val_fe7)

accuracy_fe7 = accuracy_score(y_val_fe7, y_pred_fe7)

print("XGBoost + Deck + Side + SpendingCategories Accuracy:", accuracy_fe7)
print("Accuracy (%):", accuracy_fe7 * 100)

XGBoost + Deck + Side + SpendingCategories Accuracy: 0.816561242093157
Accuracy (%): 81.65612420931569

In [83]:
spending_columns = [
    "RoomService",
    "FoodCourt",
    "ShoppingMall",
    "Spa",
    "VRDeck"
]

test["SpendingCategories"] = (
    test[spending_columns] > 0
).sum(axis=1)

test[
    ["PassengerId", "SpendingCategories"]
].head()

  PassengerId  SpendingCategories
0     0013_01                   0
1     0018_01                   2
2     0019_01                   0
3     0021_01                   3
4     0023_01                   2

In [84]:
X_test_final_2 = test.drop(
    columns=[
        "PassengerId",
        "Name",
        "Cabin"
    ]
)

X_test_final_2.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Deck,Side,SpendingCategories
0,Earth,True,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,G,S,0
1,Earth,False,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,F,S,2
2,Europa,True,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,C,S,0
3,Europa,False,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,C,S,3
4,Earth,False,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,F,S,2

In [85]:
y_test_pred_2 = xgb_fe7.predict(X_test_final_2)

# Convert 0/1 to True/False
y_test_pred_2 = y_test_pred_2.astype(bool)

print("Number of predictions:", len(y_test_pred_2))
print("First 10 predictions:")
print(y_test_pred_2[:10])

Number of predictions: 4277
First 10 predictions:
[ True False  True  True  True False  True  True  True  True]

In [86]:
submission_2 = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Transported": y_test_pred_2
})

submission_2.to_csv("submission_2.csv", index=False)

print("Submission file created successfully!")
print("Rows:", len(submission_2))
print("\nFirst 5 rows:")
print(submission_2.head())

Submission file created successfully!
Rows: 4277

First 5 rows:
  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01         True

In [87]:
!rm -f submission_2.csv

In [88]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBClassifier

# =========================================================
# 1. LOAD DATA
# =========================================================

train_raw = pd.read_csv(
    "/kaggle/input/competitions/spaceship-titanic/train.csv"
)

test_raw = pd.read_csv(
    "/kaggle/input/competitions/spaceship-titanic/test.csv"
)

y = train_raw["Transported"]


# =========================================================
# 2. FUNCTION TO TRAIN MODEL AND CREATE SUBMISSION
# =========================================================

def create_submission(train_data, test_data, filename):

    X = train_data.drop(columns=["Transported"])

    numeric_features = X.select_dtypes(
        include=["int64", "float64"]
    ).columns

    categorical_features = X.select_dtypes(
        include=["object", "bool"]
    ).columns

    preprocessor = ColumnTransformer([
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ]), numeric_features),

        ("cat", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(handle_unknown="ignore"))
        ]), categorical_features)
    ])

    model = Pipeline([
        ("preprocessor", preprocessor),

        ("model", XGBClassifier(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=4,
            subsample=0.9,
            colsample_bytree=0.9,
            random_state=42,
            eval_metric="logloss"
        ))
    ])

    # Train
    model.fit(X, y)

    # Predict
    predictions = model.predict(test_data).astype(bool)

    # Create submission
    submission = pd.DataFrame({
        "PassengerId": test_raw["PassengerId"],
        "Transported": predictions
    })

    submission.to_csv(filename, index=False)

    print(f"✅ Created: {filename}")


# =========================================================
# COMMON INFORMATION
# =========================================================

spending_columns = [
    "RoomService",
    "FoodCourt",
    "ShoppingMall",
    "Spa",
    "VRDeck"
]

train_groups = train_raw["PassengerId"].str.split("_").str[0]
test_groups = test_raw["PassengerId"].str.split("_").str[0]

group_counts = train_groups.value_counts()


# =========================================================
# 1. XGBoost + TotalSpend
# =========================================================

train_exp = train_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

test_exp = test_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

train_exp["TotalSpend"] = train_raw[
    spending_columns
].sum(axis=1)

test_exp["TotalSpend"] = test_raw[
    spending_columns
].sum(axis=1)

create_submission(
    train_exp,
    test_exp,
    "submission_totalspend.csv"
)


# =========================================================
# 2. XGBoost + Deck
# =========================================================

train_exp = train_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

test_exp = test_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

train_exp["Deck"] = train_raw["Cabin"].str.split("/").str[0]
test_exp["Deck"] = test_raw["Cabin"].str.split("/").str[0]

create_submission(
    train_exp,
    test_exp,
    "submission_deck.csv"
)


# =========================================================
# 3. XGBoost + Deck + Side
# =========================================================

train_exp = train_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

test_exp = test_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

train_exp["Deck"] = train_raw["Cabin"].str.split("/").str[0]
train_exp["Side"] = train_raw["Cabin"].str.split("/").str[2]

test_exp["Deck"] = test_raw["Cabin"].str.split("/").str[0]
test_exp["Side"] = test_raw["Cabin"].str.split("/").str[2]

create_submission(
    train_exp,
    test_exp,
    "submission_deck_side.csv"
)


# =========================================================
# 4. XGBoost + Deck + Side + GroupSize
# =========================================================

train_exp = train_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

test_exp = test_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

train_exp["Deck"] = train_raw["Cabin"].str.split("/").str[0]
train_exp["Side"] = train_raw["Cabin"].str.split("/").str[2]

test_exp["Deck"] = test_raw["Cabin"].str.split("/").str[0]
test_exp["Side"] = test_raw["Cabin"].str.split("/").str[2]

train_exp["GroupSize"] = train_groups.map(group_counts)
test_exp["GroupSize"] = test_groups.map(group_counts)

create_submission(
    train_exp,
    test_exp,
    "submission_groupsize.csv"
)


# =========================================================
# 5. XGBoost + Deck + Side + Surname
# =========================================================

train_exp = train_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

test_exp = test_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

train_exp["Deck"] = train_raw["Cabin"].str.split("/").str[0]
train_exp["Side"] = train_raw["Cabin"].str.split("/").str[2]

test_exp["Deck"] = test_raw["Cabin"].str.split("/").str[0]
test_exp["Side"] = test_raw["Cabin"].str.split("/").str[2]

train_exp["Surname"] = train_raw["Name"].str.split().str[-1]
test_exp["Surname"] = test_raw["Name"].str.split().str[-1]

create_submission(
    train_exp,
    test_exp,
    "submission_surname.csv"
)


# =========================================================
# 6. XGBoost + Deck + Side + Group
# =========================================================

train_exp = train_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

test_exp = test_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

train_exp["Deck"] = train_raw["Cabin"].str.split("/").str[0]
train_exp["Side"] = train_raw["Cabin"].str.split("/").str[2]

test_exp["Deck"] = test_raw["Cabin"].str.split("/").str[0]
test_exp["Side"] = test_raw["Cabin"].str.split("/").str[2]

train_exp["Group"] = train_groups
test_exp["Group"] = test_groups

create_submission(
    train_exp,
    test_exp,
    "submission_group.csv"
)


# =========================================================
# 7. XGBoost + Deck + Side + SpendingCategories
# =========================================================

train_exp = train_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

test_exp = test_raw.drop(
    columns=["PassengerId", "Name", "Cabin"]
).copy()

train_exp["Deck"] = train_raw["Cabin"].str.split("/").str[0]
train_exp["Side"] = train_raw["Cabin"].str.split("/").str[2]

test_exp["Deck"] = test_raw["Cabin"].str.split("/").str[0]
test_exp["Side"] = test_raw["Cabin"].str.split("/").str[2]

train_exp["SpendingCategories"] = (
    train_raw[spending_columns] > 0
).sum(axis=1)

test_exp["SpendingCategories"] = (
    test_raw[spending_columns] > 0
).sum(axis=1)

create_submission(
    train_exp,
    test_exp,
    "submission_spendingcategories.csv"
)


# =========================================================
# DONE
# =========================================================

print("\n" + "=" * 50)
print("✅ ALL 7 SUBMISSION FILES CREATED SUCCESSFULLY")
print("=" * 50)

print("""
1. submission_totalspend.csv
2. submission_deck.csv
3. submission_deck_side.csv
4. submission_groupsize.csv
5. submission_surname.csv
6. submission_group.csv
7. submission_spendingcategories.csv
""")

✅ Created: submission_totalspend.csv
✅ Created: submission_deck.csv
✅ Created: submission_deck_side.csv
✅ Created: submission_groupsize.csv
✅ Created: submission_surname.csv
✅ Created: submission_group.csv
✅ Created: submission_spendingcategories.csv

==================================================
✅ ALL 7 SUBMISSION FILES CREATED SUCCESSFULLY
==================================================

1. submission_totalspend.csv
2. submission_deck.csv
3. submission_deck_side.csv
4. submission_groupsize.csv
5. submission_surname.csv
6. submission_group.csv
7. submission_spendingcategories.csv